# Generated by Django 2.2 on 2020-07-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default='default_brand', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shampoo & Conditioner'), ('SW', 'Styling Products'), ('OW', 'Accessories')], max_length=2),
        ),
    ]
